/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TelaPrincipal;

import javax.swing.JOptionPane;

/**
 *
 * @author Diogo
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JdpPrincipal = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        Inscricao = new javax.swing.JMenu();
        jMenuInscricao = new javax.swing.JMenuItem();
        Requisicao = new javax.swing.JMenu();
        jMenuRequisicao = new javax.swing.JMenuItem();
        Reservas = new javax.swing.JMenu();
        jMenuReservas = new javax.swing.JMenuItem();
        Ajuda = new javax.swing.JMenu();
        jMenuAjuda = new javax.swing.JMenuItem();
        Sobre = new javax.swing.JMenu();
        jMenuItemTSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca Senai");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JdpPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        JdpPrincipal.setPreferredSize(new java.awt.Dimension(749, 474));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/biblioteca.jpg"))); // NOI18N

        JdpPrincipal.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout JdpPrincipalLayout = new javax.swing.GroupLayout(JdpPrincipal);
        JdpPrincipal.setLayout(JdpPrincipalLayout);
        JdpPrincipalLayout.setHorizontalGroup(
            JdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 745, Short.MAX_VALUE)
        );
        JdpPrincipalLayout.setVerticalGroup(
            JdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, Short.MAX_VALUE)
        );

        getContentPane().add(JdpPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenuBar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        Inscricao.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(0, 0, 0)));
        Inscricao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/inscrever-se.png"))); // NOI18N
        Inscricao.setPreferredSize(new java.awt.Dimension(80, 68));

        jMenuInscricao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuInscricao.setText("Abrir");
        jMenuInscricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuInscricaoActionPerformed(evt);
            }
        });
        Inscricao.add(jMenuInscricao);

        jMenuBar2.add(Inscricao);

        Requisicao.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(0, 0, 0)));
        Requisicao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/requisitos.png"))); // NOI18N
        Requisicao.setPreferredSize(new java.awt.Dimension(80, 68));

        jMenuRequisicao.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuRequisicao.setText("Abrir");
        jMenuRequisicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuRequisicaoActionPerformed(evt);
            }
        });
        Requisicao.add(jMenuRequisicao);

        jMenuBar2.add(Requisicao);

        Reservas.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(0, 0, 0)));
        Reservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/reserve.png"))); // NOI18N
        Reservas.setPreferredSize(new java.awt.Dimension(80, 68));

        jMenuReservas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuReservas.setText("Abrir");
        jMenuReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuReservasActionPerformed(evt);
            }
        });
        Reservas.add(jMenuReservas);

        jMenuBar2.add(Reservas);

        Ajuda.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(0, 0, 0)));
        Ajuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ajuda.png"))); // NOI18N
        Ajuda.setPreferredSize(new java.awt.Dimension(80, 68));

        jMenuAjuda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuAjuda.setText("Abrir");
        jMenuAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAjudaActionPerformed(evt);
            }
        });
        Ajuda.add(jMenuAjuda);

        jMenuBar2.add(Ajuda);

        Sobre.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(0, 0, 0)));
        Sobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/info.png"))); // NOI18N
        Sobre.setPreferredSize(new java.awt.Dimension(80, 68));

        jMenuItemTSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_5, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItemTSobre.setText("Abrir");
        jMenuItemTSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTSobreActionPerformed(evt);
            }
        });
        Sobre.add(jMenuItemTSobre);

        jMenuBar2.add(Sobre);

        setJMenuBar(jMenuBar2);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuInscricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuInscricaoActionPerformed
        TelaInscricao carregar = new TelaInscricao();
        JdpPrincipal.add(carregar);
        carregar.setVisible(true);
        
    }//GEN-LAST:event_jMenuInscricaoActionPerformed

    private void jMenuRequisicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuRequisicaoActionPerformed
        TelaRequisicao carregar = new TelaRequisicao();
        JdpPrincipal.add(carregar);
        carregar.setVisible(true);
        
    }//GEN-LAST:event_jMenuRequisicaoActionPerformed

    private void jMenuReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuReservasActionPerformed
        TelaReservas carregar = new TelaReservas();
        JdpPrincipal.add(carregar);
        carregar.setVisible(true);
        
    }//GEN-LAST:event_jMenuReservasActionPerformed

    private void jMenuAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAjudaActionPerformed
        Ajuda();
        
    }//GEN-LAST:event_jMenuAjudaActionPerformed

    private void jMenuItemTSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTSobreActionPerformed
        TelaSobre carregar = new TelaSobre();
        JdpPrincipal.add(carregar);
        carregar.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemTSobreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Ajuda;
    private javax.swing.JMenu Inscricao;
    private javax.swing.JDesktopPane JdpPrincipal;
    private javax.swing.JMenu Requisicao;
    private javax.swing.JMenu Reservas;
    private javax.swing.JMenu Sobre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuAjuda;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuInscricao;
    private javax.swing.JMenuItem jMenuItemTSobre;
    private javax.swing.JMenuItem jMenuRequisicao;
    private javax.swing.JMenuItem jMenuReservas;
    // End of variables declaration//GEN-END:variables

    private void Ajuda() {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    
    String chmfile = "cmd.exe /c ajuda.chm";
        Runtime run = Runtime.getRuntime();
        try {
            run.exec(chmfile);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
 
    }

}
